version: "3.3"
services:
  nginx:
    image: nginx:1.15
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      # app
      - ./app:/usr/share/nginx/html
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro